<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Isabela Cristancho- Lesly Triana">

<title>TALLER 27 FEBRERO</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="TALLER 27 FEBRERO ISABELA CRISTANCHO  LESLY TRIANA_files/libs/clipboard/clipboard.min.js"></script>
<script src="TALLER 27 FEBRERO ISABELA CRISTANCHO  LESLY TRIANA_files/libs/quarto-html/quarto.js"></script>
<script src="TALLER 27 FEBRERO ISABELA CRISTANCHO  LESLY TRIANA_files/libs/quarto-html/popper.min.js"></script>
<script src="TALLER 27 FEBRERO ISABELA CRISTANCHO  LESLY TRIANA_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="TALLER 27 FEBRERO ISABELA CRISTANCHO  LESLY TRIANA_files/libs/quarto-html/anchor.min.js"></script>
<link href="TALLER 27 FEBRERO ISABELA CRISTANCHO  LESLY TRIANA_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="TALLER 27 FEBRERO ISABELA CRISTANCHO  LESLY TRIANA_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="TALLER 27 FEBRERO ISABELA CRISTANCHO  LESLY TRIANA_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="TALLER 27 FEBRERO ISABELA CRISTANCHO  LESLY TRIANA_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="TALLER 27 FEBRERO ISABELA CRISTANCHO  LESLY TRIANA_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">TALLER 27 FEBRERO</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Isabela Cristancho- Lesly Triana </p>
          </div>
  </div>
    
    
  </div>
  

</header>

<section id="taller-27-febrero" class="level2">
<h2 class="anchored" data-anchor-id="taller-27-febrero"><span class="smallcaps"><strong>TALLER 27 FEBRERO</strong></span></h2>
<p><em>EJERCICIO C 3.1</em></p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bwght ~ cigs + faminc, data = bwght)

Residuals:
    Min      1Q  Median      3Q     Max 
-96.061 -11.543   0.638  13.126 150.083 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 116.97413    1.04898 111.512  &lt; 2e-16 ***
cigs         -0.46341    0.09158  -5.060 4.75e-07 ***
faminc        0.09276    0.02919   3.178  0.00151 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 20.06 on 1385 degrees of freedom
Multiple R-squared:  0.0298,    Adjusted R-squared:  0.0284 
F-statistic: 21.27 on 2 and 1385 DF,  p-value: 7.942e-10</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.1730449</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bwght ~ cigs, data = bwght)

Residuals:
    Min      1Q  Median      3Q     Max 
-96.772 -11.772   0.297  13.228 151.228 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 119.77190    0.57234 209.267  &lt; 2e-16 ***
cigs         -0.51377    0.09049  -5.678 1.66e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 20.13 on 1386 degrees of freedom
Multiple R-squared:  0.02273,   Adjusted R-squared:  0.02202 
F-statistic: 32.24 on 1 and 1386 DF,  p-value: 1.662e-08</code></pre>
</div>
</div>
<table class="table">
<colgroup>
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Estimate</th>
<th>Std.Error</th>
<th>t value</th>
<th>p value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Intercept</strong></td>
<td><pre><code>119.77190</code></pre></td>
<td><pre><code>0.57234</code></pre></td>
<td><pre><code>209.267</code></pre></td>
<td><pre><code>&lt; 2e-16 ***</code></pre></td>
</tr>
<tr class="even">
<td><strong>Cigs</strong></td>
<td><pre><code>-0.51377</code></pre></td>
<td><pre><code>0.09049</code></pre></td>
<td><pre><code>-5.678</code></pre></td>
<td><pre><code>1.66e-08 ***</code></pre></td>
</tr>
</tbody>
</table>
<table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 17%">
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Estimate</th>
<th>Std. Error</th>
<th>t.value</th>
<th>P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Intercept</strong></td>
<td><pre><code>116.97413</code></pre></td>
<td><pre><code>1.04898</code></pre></td>
<td><pre><code>111.512</code></pre></td>
<td><pre><code>&lt; 2e-16 ***</code></pre></td>
</tr>
<tr class="even">
<td><strong>cigs (fumar)</strong></td>
<td><pre><code>-0.46341</code></pre></td>
<td><pre><code> 0.09158</code></pre></td>
<td><pre><code>-5.060</code></pre></td>
<td><pre><code>4.75e-07 ***</code></pre></td>
</tr>
<tr class="odd">
<td><strong>faminc (ingresos)</strong></td>
<td><pre><code> 0.09276</code></pre></td>
<td><pre><code>0.02919</code></pre></td>
<td><pre><code>3.178</code></pre></td>
<td><pre><code>0.00151 **</code></pre></td>
</tr>
</tbody>
</table>
<ol type="1">
<li>El signo para faminc mas probable es positivo, se espera que al tener mas ingresos durante el embarazo tenga un efecto positivo en el peso al nacer,ya que con mas ingresos hay mejores cuidados.</li>
<li>Las variables cigs y faminc tienen una correlacion negativa (-0.1730449), cuando una variable aumenta (x), la otra (y) disminuye. Es decir, las mujeres de ingresos más altos tienen acceso a mejores cuidados prenatales y a una mejor nutrición y es posible que también tengan más conciencia de los riesgos de fumar durante el embarazo y sean menos propensas a fumar.Por eso, la correlación entre cigs y faminc sería negativa.</li>
<li>Al quitar la variable faminc de la ecuacion,el estimado de cigs es -0.51377, no tiene un cambio drástico en la variable cigs porque al incluir faminc en la ecuacion el estimado para cigs es de -0.46341, por lo tanto faminc no tiene un efecto sustancial en el peso al nacer y cigs es la variable más relevante en el modelo y al revisar el R cuadrado tiene 2.98% de variabilidad con faminc y sin faminc tiene 2.27% de variabilidad”</li>
</ol>
<p><em>EJERCICIO C 3.2</em></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ bdrms + sqrft, data = hprice1)

Residuals:
     Min       1Q   Median       3Q      Max 
-127.627  -42.876   -7.051   32.589  229.003 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -19.31500   31.04662  -0.622    0.536    
bdrms        15.19819    9.48352   1.603    0.113    
sqrft         0.12844    0.01382   9.291 1.39e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 63.04 on 85 degrees of freedom
Multiple R-squared:  0.6319,    Adjusted R-squared:  0.6233 
F-statistic: 72.96 on 2 and 85 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5314736</code></pre>
</div>
</div>
<table class="table">
<colgroup>
<col style="width: 30%">
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Estimate</th>
<th>Std. Error</th>
<th>t value</th>
<th>p value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Intercept</strong></td>
<td><pre><code>-19.31500</code></pre></td>
<td><pre><code>31.04662</code></pre></td>
<td><pre><code>-0.622</code></pre></td>
<td><pre><code> 0.536</code></pre></td>
</tr>
<tr class="even">
<td><strong>bdrms (habitación)</strong></td>
<td><pre><code>15.19819</code></pre></td>
<td><pre><code>9.48352</code></pre></td>
<td><pre><code> 1.603</code></pre></td>
<td><pre><code>0.113</code></pre></td>
</tr>
<tr class="odd">
<td><strong>sqrft (pies cuadrados)</strong></td>
<td><pre><code>0.12844</code></pre></td>
<td><pre><code> 0.01382</code></pre></td>
<td><pre><code>9.291</code></pre></td>
<td><pre><code>1.39e-14 ***</code></pre></td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       1 
354.6052 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       1 
299645.4 </code></pre>
</div>
</div>
<ol type="1">
<li>price=-19.31500 + 15.19819 + 0.12844</li>
<li>Si aumenta una habitacion mas en bdrms puede aumentar 15.19819 miles de dolares en el precio.</li>
<li></li>
<li>La variación del precio es de 63.19% en cuanto a la extensión en pies cuadrados y el número de habitaciones</li>
<li>El estimado del precio para la primer casa cuando sqrft 2,438 y bdrms 4 es de 354.6052 miles de dolares</li>
<li>Cuando el precio de la primer casa es de 300.000, el residual es de 299645.4, es decir la diferencia entre el precio real y el estimado, por ende, el comprador pago mas por la casa, debido a que el precio real es mayor que el precio estimado</li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>